#pragma config(Sensor, S1,     US1,            sensorI2CCustom9V)
#pragma config(Sensor, S2,     US2,            sensorI2CCustom9V)
#pragma config(Sensor, S3,     US3,            sensorI2CCustom9V)
#pragma config(Sensor, S4,     US4,            sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Xander Soldaat's 'Third Party Driver' for the LEGO Sonar */
#include "drivers/lego-ultrasound.h"

task main()
{
	int Dist1 = 0;
  while(true)
  {
    nxtDisplayClearTextLine(5);
    USsetSingleMode(US1);                 // Set US1 Sensor in Single Shot Mode
    wait1Msec(50);                        // Wait to Capture Distance Value
    Dist1 = USreadDist(US1);              // Read the Sonar Sensor's Distance Value
    nxtDisplayTextLine(5, "%d", Dist1);
    USsetOff(US1);                        // Turn off Sonar Sensor on Digital ports 1
   }
}
